# Instruction:  https://github.com/marketplace/actions/typos-action#getting-started
[default.extend-words]
JSUT = "JSUT"
jsut = "jsut"
inout = "inout"

[default.extend-identifiers]

[files]
extend-exclude = ["*.hed"]
