# @package _group_

out_dir: exp
nepochs: 200
checkpoint_epoch_interval: 20

stream_wise_loss: false
use_detect_anomaly: true

optim:
  optimizer:
    name: Adam
    params:
      lr: 0.001
      betas: [0.9, 0.999]
      weight_decay: 0.0
  lr_scheduler:
    name: StepLR
    params:
      step_size: 50
      gamma: 0.5

resume:
  checkpoint:
  load_optimizer: false

cudnn:
  benchmark: false
  deterministic: true
